Update data_utils.py (#104)
* Update data_utils.py

Solving a minor issue during the usage of the name_to_dataset function raising the error

UnboundLocalError: local variable 'dataset' referenced before assignment

* Update data_utils.py

Found the source of the problem, one of the datasets was an empty string because I forgot a comma :)
Just putting the error if anyone has this issue so you can incorporate it if you find it useful, if not please disregard this PR

DATASETS="\
dataset1,\
dataset2,\
"

instead of

DATASETS="\
dataset1,\
dataset2\
"